### ISSUE TITLE
Setting up a root

### ISSUE THREAD

**Issue by stefangeorg** [OpenAgricultureFoundation/gro-api#1]
Is there no current way to create a root server, only leaves? Also there is a lack of documentation about the meaning of these terms, what is the difference between a leaf and a root, and are both required or can a leaf operate without any root?

I'm also getting this for every API endpoint:

http://ikemori.xyz/user/

HTTP 403 Forbidden
Vary: Accept
Allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json

{
    "detail": "Please configure your farm before attempting to save data in this API"
}

But no documentation on how to setup a farm.

I created the initial data with the loadinitialdata command.

Any other help would be appreciated

**Comment by LeonChambers** [comment]
Yes, only leaves are implemented right now. The idea was that each food computer instance is a leaf server that mirrors its data to a central root server. We implemented the leaf servers first so that we could start deploying machines before developing the data mirroring stuff. So yes, a leaf can operate without a root.

To fix that error, you have to edit the Farm object at "/farm/1/". In particular, a value for the "layout" attribute must be provided. You probably want to set the value to "tray".

Documentation is pretty spare right now because we're working on redesigning a lot of the software stack. We actually aren't using the code from this repo on any of our new machines at the moment.

**Comment by serein7** [comment]
@LeonChambers 
> We actually aren't using the code from this repo on any of our new machines at the moment.
Does that mean that new version of PFC will not use Raspberry or you are just moving to a different software architecture?

**Comment by caveman2st** [comment]
>Documentation is pretty spare right now because we're working on redesigning a lot of the software stack. We actually aren't using the code from this repo on any of our new machines at the moment.

i have exactly the same problem. 
But as i read your lines I’m not sure if and how to continue to participate in the project.
Why is the ongoing work of the dev project not public as in general promised?

**Comment by rklosinski** [comment]
The on-going work is not at the state that it can be released.

Regards,
Rich

**Comment by caveman2st** [comment]
Hi Rich, 
there is a lot of marketing info and twitter stuff but i can't find concrete info about development: new concepts, plans, timelines, kind of participation, ...
Regards Stefan

**Comment by rklosinski** [comment]
MIT is really still defining architecture of the hardware and software of
version 2.0.

Regards,
Rich

**Comment by LeonChambers** [comment]
Hey guys,

I just opened up the repository for the current backend work. The link is [here](https://github.com/OpenAgInitiative/openag-brain). Again, there is not much in the way of documentation yet because it's pretty new code. I'll try to write up a brief description of the architecture, some installation instructions, and such when I get a chance.

**Comment by serein7** [comment]
@LeonChambers
Great! Thank you. 

I see that you are utilizing CouchDb for persistance replacing  sqlite in v1. Promising choice!
